class Square < ActiveRecord::Base
	belongs_to(:game)
	# spots = Square.all
	# render(:json => {:matches => matches.to_json({:include => :winner}), :win_percentage => percentage.to_json})

	def self.create
		Square.create(:game_id => gm1.id, :x => 1, :y => 1, :contents => "br")
		Square.create(:game_id => gm1.id, :x => 2, :y => 1, :contents => "bn")
		Square.create(:game_id => gm1.id, :x => 3, :y => 1, :contents => "bb")
		Square.create(:game_id => gm1.id, :x => 4, :y => 1, :contents => "bq")
		Square.create(:game_id => gm1.id, :x => 5, :y => 1, :contents => "bk")
		Square.create(:game_id => gm1.id, :x => 6, :y => 1, :contents => "bb")
		Square.create(:game_id => gm1.id, :x => 7, :y => 1, :contents => "bk")
		Square.create(:game_id => gm1.id, :x => 8, :y => 1, :contents => "br")

		Square.create(:game_id => gm1.id, :x => 1, :y => 2, :contents => "bp")
		Square.create(:game_id => gm1.id, :x => 2, :y => 2, :contents => "bp")
		Square.create(:game_id => gm1.id, :x => 3, :y => 2, :contents => "bp")
		Square.create(:game_id => gm1.id, :x => 4, :y => 2, :contents => "bp")
		Square.create(:game_id => gm1.id, :x => 5, :y => 2, :contents => "bp")
		Square.create(:game_id => gm1.id, :x => 6, :y => 2, :contents => "bp")
		Square.create(:game_id => gm1.id, :x => 7, :y => 2, :contents => "bp")
		Square.create(:game_id => gm1.id, :x => 8, :y => 2, :contents => "bp")

		Square.create(:game_id => gm1.id, :x => 1, :y => 3, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 2, :y => 3, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 3, :y => 3, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 4, :y => 3, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 5, :y => 3, :contents => "bb")
		Square.create(:game_id => gm1.id, :x => 6, :y => 3, :contents => "rook")
		Square.create(:game_id => gm1.id, :x => 7, :y => 3, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 8, :y => 3, :contents => "nil")

		Square.create(:game_id => gm1.id, :x => 1, :y => 4, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 2, :y => 4, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 3, :y => 4, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 4, :y => 4, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 5, :y => 4, :contents => "bq")
		Square.create(:game_id => gm1.id, :x => 6, :y => 4, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 7, :y => 4, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 8, :y => 4, :contents => "nil")

		Square.create(:game_id => gm1.id, :x => 1, :y => 5, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 2, :y => 5, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 3, :y => 5, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 4, :y => 5, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 5, :y => 5, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 6, :y => 5, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 7, :y => 5, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 8, :y => 5, :contents => "nil")

		Square.create(:game_id => gm1.id, :x => 1, :y => 6, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 2, :y => 6, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 3, :y => 6, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 4, :y => 6, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 5, :y => 6, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 6, :y => 6, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 7, :y => 6, :contents => "nil")
		Square.create(:game_id => gm1.id, :x => 8, :y => 6, :contents => "nil")

		Square.create(:game_id => gm1.id, :x => 1, :y => 7, :contents => "wp")
		Square.create(:game_id => gm1.id, :x => 2, :y => 7, :contents => "wp")
		Square.create(:game_id => gm1.id, :x => 3, :y => 7, :contents => "wp")
		Square.create(:game_id => gm1.id, :x => 4, :y => 7, :contents => "wp")
		Square.create(:game_id => gm1.id, :x => 5, :y => 7, :contents => "wp")
		Square.create(:game_id => gm1.id, :x => 6, :y => 7, :contents => "wp")
		Square.create(:game_id => gm1.id, :x => 7, :y => 7, :contents => "wp")
		Square.create(:game_id => gm1.id, :x => 8, :y => 7, :contents => "wp")

		Square.create(:game_id => gm1.id, :x => 1, :y => 8, :contents => "wr")
		Square.create(:game_id => gm1.id, :x => 2, :y => 8, :contents => "wn")
		Square.create(:game_id => gm1.id, :x => 3, :y => 8, :contents => "wb")
		Square.create(:game_id => gm1.id, :x => 4, :y => 8, :contents => "wq")
		Square.create(:game_id => gm1.id, :x => 5, :y => 8, :contents => "wk")
		Square.create(:game_id => gm1.id, :x => 6, :y => 8, :contents => "wb")
		Square.create(:game_id => gm1.id, :x => 7, :y => 8, :contents => "wn")
		Square.create(:game_id => gm1.id, :x => 8, :y => 8, :contents => "wr")
	end
end
